DROP TABLE IF EXISTS ACCT_TABLE;
DROP SEQUENCE IF EXISTS ACCOUNT_SEQUENCE;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS ACCT_TABLE
(
   ACCOUNT_ID BIGINT NOT NULL,
   ACCOUNT_NUMBER CHARACTER VARYING (255) NOT NULL,
   ACCOUNT_TYPE CHARACTER VARYING (255) NOT NULL,
   CREATED_DATE TIMESTAMP NOT NULL,
   STS CHARACTER VARYING (64) NOT NULL
)
WITH(
    OIDS=FALSE
);


CREATE SEQUENCE IF NOT EXISTS ACCOUNT_SEQUENCE
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 99999999999
    START 1
    CACHE 1;